[package]
name = "mathvis"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive_more = "0.99.18"
nom = "7.1.3"
num = "0.4.3"
thiserror = "1.0.69"

[dev-dependencies]
rand = "0.8.5"
