[package]
name = "mathvis"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive_more = {version = "1.0.0", features = ["display"]}
nom = "7.1.3"
num = "0.4.3"
thiserror = "2.0.11"

[dev-dependencies]
rand = "0.8.5"
